# Generated by Django 4.1.3 on 2023-01-17 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Commute",
        ),
        migrations.DeleteModel(
            name="Pay",
        ),
        migrations.RemoveField(
            model_name="vacation",
            name="user_name",
        ),
        migrations.DeleteModel(
            name="Working_condition",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="Vacation",
        ),
    ]
