# Generated by Django 4.1.3 on 2023-01-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="commute",
            name="user_email",
            field=models.ForeignKey(
                db_column="user_email",
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commute",
                to="main.user",
                to_field="user_email",
            ),
        ),
        migrations.AddField(
            model_name="pay",
            name="user_email",
            field=models.ForeignKey(
                db_column="user_email",
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pay",
                to="main.user",
                to_field="user_email",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="user_email",
            field=models.ForeignKey(
                db_column="user_email",
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="main.user",
                to_field="user_email",
            ),
        ),
        migrations.AddField(
            model_name="vacation",
            name="user_email",
            field=models.ForeignKey(
                db_column="user_email",
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacation_email",
                to="main.user",
                to_field="user_email",
            ),
        ),
        migrations.AddField(
            model_name="working_condition",
            name="user_email",
            field=models.ForeignKey(
                db_column="user_email",
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work",
                to="main.user",
                to_field="user_email",
            ),
        ),
        migrations.AlterField(
            model_name="vacation",
            name="user_name",
            field=models.ForeignKey(
                db_column="user_name",
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacation_name",
                to="main.user",
            ),
        ),
    ]
